### ISSUE TITLE
For loop initialization errors

### ISSUE THREAD

**Issue by franslundberg** [assaabloy-ppi/binson-c-light#1]
I get compile errors like the following:

binson_light.c: In function ‘_binson_util_unpack_integer’:
binson_light.c:647:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i=bsize-1; i>=0; i--)

Perhaps the few cases of for-loop initialization could be changed? I am using default GCC on Ubuntu (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1))

**Comment by ppmag** [comment]
Quick answer is:  just pls add "-std=c99" to your gcc compile option list of your project.

Long answer:
gcc does not conform to any of the ANSI/ISO C standards by default,
gcc has C dialect set to -std=gnu11 by default.

To maximize portability and allow usage of modern but still ISO features of  C language, dialect c99 was used for binson-c-light project.

PS:  by usage of separate gcc build stages it's possible to have user's code be in any standard, but "binson_light.c" must be built with "-std=c99" option.
