### ISSUE TITLE
#define bool int give troubles when compiling with a C++ compiler.

### ISSUE THREAD

**Issue by rosbacke** [assaabloy-ppi/binson-c-light#13]
In binson_light.h we have this little gem:
#ifndef bool
#define bool        int   /* for 8-bit platforms better to use int8_t instead */
#define true        1
#define false       0
#endif

When compiling with a C++ compiler, bool isn't defined but rather a fundamental type. This code with promptly define it to int.

Later on, in a normal program if you ever include type_traits (via e.g. standard string) you will get a compile error complaining about multiple template instantiations between int and bool. (Sort of confusing.).

Replacing the #ifndef condition above with e.g. 
#if !defined(bool) && !defined(__cplusplus)
should fix this particular issue.

As a general note, for C99 you should do:
#include <stdbool.h>
instead of doing your own defines.

/ MR

**Comment by ppmag** [comment]
thank you, fixed!
