### ISSUE TITLE
Can't access multiple identical objects in one binson packet.

### ISSUE THREAD

**Issue by SylwBar** [assaabloy-ppi/binson-c-light#14]
After updating QuickCheck model for binson parser it revealed potential problem with accessing fields in objects.
QC provided minimal vector showing problem:
{64,20,1,65,64,20,1,66,16,1,65,65};
which, described as Erlang term is : #{"A" => #{"A" => 1}} - object with field "A" storing object with field "A" storing value 1.
Program exposing problem shows that value 1 can't be accessed:
```

#include <stdio.h>
#include "binson_light.h"

int main(void)
{
    binson_parser p;

    uint8_t  src[256];
    uint8_t  buf[256];

    //#{"A" => #{"A" => 1}}
    const uint8_t b1[]  ={64,20,1,65,64,20,1,65,16,1,65,65};

    memcpy( src, b1, sizeof(b1) );
    binson_parser_init( &p, src, sizeof(src) );

    binson_parser_go_into( &p );
    binson_parser_field( &p, "A" );
    printf("Status: %x\n", p.error_flags);

    binson_parser_go_into( &p );
    binson_parser_field( &p, "A" );
    printf("Status: %x\n", p.error_flags);

    printf("int: %d\n", (int)binson_parser_get_integer(&p));
    printf("Status: %x\n", p.error_flags);
    return 0;
}

Status: 0
Status: 0
int: 0
Status: 0

```
When the field names are different value 1 is returned. 
There is requirement from: binson.org which says something about it:

> 4. Two fields of the same object cannot have the same name.

But it is not clear whether two fields means - two fields in whole binson packet or rather two fields of the same "object" which is understood as binson data type: 

> object     = begin *field end

I assumed second - there should be no identical fields on selected object level, but they could appear on different objects - also in nested objects.

To move reader toward my understanding I figured out such scenario: someone wants to send array of identical objects in one binson packet.
Erlang term describing such item should look like this:
#{"objs" => {#{"id" => 1},#{"id" => 2}}}
Byte representation:
```
> binson:encode(#{"objs" => {#{"id" => 1},#{"id" => 2}}}).
<<64,20,4,111,98,106,115,66,64,20,2,105,100,16,1,65,64,20,2,105,100,16,2,65,67,65>>

```
Example program for accessing object's id:

```
#include <stdio.h>
#include "binson_light.h"

int main(void)
{
    binson_parser p;

    uint8_t  src[256];
    uint8_t  buf[256];

    //#{"objs" => {#{"id" => 1},#{"id" => 2}}}
    const uint8_t b1[]  ={64,20,4,111,98,106,115,66,64,20,2,105,100,16,1,65,64,20,2,105,100,16,2,65,67,65};

    memcpy( src, b1, sizeof(b1) );
    binson_parser_init( &p, src, sizeof(src) );

    binson_parser_go_into( &p );
    binson_parser_field( &p, "objs" );
    printf("Status: %x\n", p.error_flags);

    binson_parser_go_into_array( &p );
    printf("Status: %x\n", p.error_flags);

    binson_parser_go_into( &p );
    binson_parser_field( &p, "id" );
    printf("Status: %x\n", p.error_flags);

    printf("int: %d\n", (int)binson_parser_get_integer(&p));
    printf("Status: %x\n", p.error_flags);

    binson_parser_go_up( &p );
    binson_parser_next( &p );

    binson_parser_go_into( &p );
    binson_parser_field( &p, "id" );
    printf("Status: %x\n", p.error_flags);

    printf("int: %d\n", (int)binson_parser_get_integer(&p));
    printf("Status: %x\n", p.error_flags);

    return 0;
}

Status: 0
Status: 0
Status: 0
int: 1
Status: 0
Status: 0
int: 1
Status: 0

```

Shows two "1". After changing names to be different correct result is observed.

Conclusion:
Second presented example shows possible scenario - user wants to send multiple identical objects in one binson file.
With current implementation accessing such objects is not possible using presented API (but maybe possible with other way).

**Comment by ppmag** [comment]
Thank you for such a detailed report!
Item name now become stored in stack structure on block enter + restored on block end to continue relevant search after return to upper level.

Please note, there is still the issue with subsequent search of one-level items with same name
e.g. {"a": 1, "a": 2, "a": 3}
We can't move forward in this case with binson_parser_field( &p, "a" );
due to optional fields functionality (pls see #6).
Anyway, even in this case we can still advance with binson_parser_next(&p);

Alex.

**Comment by SylwBar** [comment]
_Please note, there is still the issue with subsequent search of one-level items with same name
e.g. {"a": 1, "a": 2, "a": 3}_
This is perfectly OK because of requirement from binson.org :
_4. Two fields of the same object cannot have the same name._

**Comment by SylwBar** [comment]
I confirm that above failing scenario was fixed but surprisingly, after longer testing QuickCheck revealed one scenario that exposes problem with identical field naming.
For this value: #{"B" => #{"A" => #{},"B" => 1}} it is not possible to get value "1" from second field "B".
Binson representation:
const uint8_t b1[]  ={64,20,1,66,64,20,1,65,64,65,20,1,66,16,1,65,65};
It is possible to get correct result when:
- first "B" field has different name,
- "A" object is not object - I tested it when A was 1

Second case is interesting and I will clarify: when A is something different than object it is possible to get value "1" of second field "B" when there is also "B" field on top level.

Code example:
```
#include <stdio.h>
#include "binson_light.h"

int main(void)
{
    binson_parser p;

    uint8_t  src[256];

    //Value: #{"B" => #{"A" => #{},"B" => 1}}
    const uint8_t b1[]  ={64,20,1,66,64,20,1,65,64,65,20,1,66,16,1,65,65};

    memcpy( src, b1, sizeof(b1) );
    binson_parser_init( &p, src, sizeof(src) );

    binson_parser_go_into( &p );
    binson_parser_field( &p, "B" );
    printf("Status: %x\n", p.error_flags);

    binson_parser_go_into( &p );
    printf("Status: %x\n", p.error_flags);

    binson_parser_field( &p, "A" );
    printf("Status: %x\n", p.error_flags);

    binson_parser_go_into( &p );
    binson_parser_go_up( &p );

    binson_parser_field( &p, "B" );
    printf("Status: %x\n", p.error_flags);

    printf("int: %d\n", (int)binson_parser_get_integer(&p));
    printf("Status: %x\n", p.error_flags);

    return 0;
}

Status: 0
Status: 0
Status: 0
Status: 0
int: 0
Status: 0


```

**Comment by ppmag** [comment]
Very interesting! Working on it...

**Comment by ppmag** [comment]
It was bug in the fix code :(
Let's try one more time...

**Comment by SylwBar** [comment]
OK, passed 100000 tests

**Comment by franslundberg** [comment]
> I assumed second - there should be no identical fields on selected object
level, but they could appear on different objects - also in nested objects.
Yes, that is what I meant in the spec. I suppose it should be clearified.

Thanks for noting this.
/ Frans
