### ISSUE TITLE
Possible enhancement, add length field for string operations

### ISSUE THREAD

**Issue by sijohans** [assaabloy-ppi/binson-c-light#16]
It is generally a good idea to send in a length when working with strings, therefore, i propose that e.g. the function binson_parser_cmp_string also should take a length argument. If looking at performance, i think we could also win some if doing this. For instance these two functions:

```c
/* Compare two bytearrays in lexicographical sense.  return value same as  strcmp() */
int binson_util_cmp_bbuf2bbuf( bbuf *bb1, bbuf *bb2 )
{
  int r = memcmp( bb1->bptr, bb2->bptr, MIN(bb1->bsize, bb2->bsize) );
  return (r == 0)? (int)(bb1->bsize - bb2->bsize) : r;
}

/* Compare zero-terminated string with bytearrays in lexicographical sense.  return value same as  strcmp() */
int binson_util_cmp_bbuf2asciiz( bbuf *bb1, const char* pstr )
{
  bbuf bb2 = { .bptr = (uint8_t*)pstr, .bsize = (binson_tok_size)strlen(pstr) };
  return binson_util_cmp_bbuf2bbuf( bb1, &bb2 );
}
```

Might actually loop through the whole string two times. The first time when deciding the length (let's hope that the string is null terminated, or a null termination character is not to far away in memory) using **strlen**. The second time when doing the **memcmp**.

**Comment by ppmag** [comment]
I agree, length calculation is redundant if length already known for caller,
for this particular case one proposed solution is to **add** next top level API calls,

```c
int binson_parser_cmp_string_bbuf( binson_parser *pp, bbuf *str_bb )
{
  return binson_util_cmp_bbuf2bbuf( &pp->val.bbuf_val, str_bb );
}

bool binson_parser_string_equals_bbuf( binson_parser *pp, bbuf *str_bb )
{
  return binson_parser_cmp_string_bbuf( pp, str_bb )==0? true:false;
}
```

In C99 it's possible to use it inline without separate line with bbuf declaration
and initialization:
```c
binson_parser_cmp_string_bbuf( pp, &(bbuf){ .bptr = pstr, .bsize = (binson_tok_size)pstr_len } );
```
As an alternative,
it's possible to provide "default" length argument to original function, let's say:

```c
int binson_parser_cmp_string( binson_parser *pp, const char *pstr,  binson_tok_size len_default)
{
  bbuf bb2 = { .bptr = (uint8_t*)pstr, .bsize = len_default? len_default : (binson_tok_size)strlen(pstr) };
  return binson_util_cmp_bbuf2bbuf( &pp->val.bbuf_val, &bb2 );
}
```
Which way you like more from integration POV, etc?

**Comment by sijohans** [comment]
Hello, i'm not really sure. However, this is an easy fix, we could probably implement it when we know more what we want from the API.

**Comment by ppmag** [comment]
yes,  ok
