### ISSUE TITLE
User defined max object depth

### ISSUE THREAD

**Issue by sijohans** [assaabloy-ppi/binson-c-light#34]
Right now the maximum object depth is defined in the header file (binson_parser.h) and is compiled with this option. It would be a nice feature for the used to be able to specify this. The requirement for no dynamic memory allocation makes this a little bit harder.

The following structure is used:
```c
struct binson_parser_s {
    ...
    uint_fast8_t    depth;
    binson_state    state[BINSON_PARSER_MAX_DEPTH];
    ...
};
'```

The state array is needed for keeping track of depths, field names etc for verifying that the object is valid. If the state array instead would be changed to a pointer, and that a length parameter is provided, the maximum depth will not be hard coded. I.e.:
```c
struct binson_parser_s {
    ...
    uint_fast8_t    depth;
    uint_fast8_t    max_depth;
    binson_state    *state;
    ...
};
```

If changing this it is hard to obtain backwards compatibility. I.e., defining a parser like this:
```c
binson_parser p;
binson_parser_init(&p, my_data, my_data_size);
```

I want to start a discussion of if we want this feature, and how we should implement it to make the impact as small as possible. I see several possible solutions to this, i will post some suggestion (when there is time).

**Comment by franslundberg** [comment]
Personally, I am not that much against dynamic memory allocation at *initialization time*. During ordinary runtime is a different story. But doing initial allocation dynamically or statically does not matter much, I think. Please correct me when I am wrong. Dynamic mem alloc is more flexible since it can be parameterized after compile-time. I do fancy the pre-processor that much.

**Comment by sijohans** [comment]
The solution above works pretty well. A macro can be used to simplify the definition of the parser:
```c
#define BINSON_PARSER_DEFAULT_DEPTH     (10U)
#define BINSON_PARSER_DEF_DEPTH(p, depth)           \
    binson_state p##data##__LINE__[depth];          \
    binson_parser p;                                \
    p.max_depth = depth;                            \
    p.state = p##data##__LINE__
#define BINSON_PARSER_DEF(p) BINSON_PARSER_DEF_DEPTH(p, BINSON_PARSER_DEFAULT_DEPTH)

/* In C file */
BINSON_PARSER_DEF(p);
binson_parser_init(&p);
binson_parser_go_into_object(&p);
...
```

However, to use another maximum depth one would need to use another macro. This can also be solved with macros:
```c
BINSON_PARSER_DEF(p);     /* Default depth */
BINSON_PARSER_DEF(p, 5); /* Maximum 5 depth */
```

But if doing that seems to be a GNU extension. I.e., it is not that portable. So probably the two macro solution is better.

**Comment by sijohans** [comment]
This approach is visible in this branch: https://github.com/assaabloy-ppi/binson-c-light/tree/user-defined-depth

I also made an alternative:
```sh
binson_parser p = BINSON_PARSER(4); // Can parse up to four nested object
```
