### ISSUE TITLE
Confusing binson transcription

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/binson-c-light#40]
Looks like this line
https://github.com/assaabloy-ppi/binson-c-light/blob/master/utest/binson_parser_test.c#L850

should be 
```
/* [{"A":["A"]}] */
```

**Comment by sijohans** [comment]
Yes that is correct, it is a raw binson array.

**Comment by sijohans** [comment]
Fixed 426ff8056c0093c063835cebec6e6defc24208c9
