### ISSUE TITLE
Does not compile with IAR compiler

### ISSUE THREAD

**Issue by sijohans** [assaabloy-ppi/binson-c-light#7]
When trying to compile the binson_light.c with the IAR compiler we get compile error.

By changing 
```c
bbuf*  binson_parser_get_string_bbuf( binson_parser *pp )
{
  //  return  &pp->val.bbuf_val;
  return (pp->val_type == BINSON_ID_STRING)? &pp->val.bbuf_val : (pp->error_flags = BINSON_ID_PARSE_WRONG_TYPE, NULL);
}
```
to
```c
bbuf*  binson_parser_get_string_bbuf( binson_parser *pp )
{
  //  return  &pp->val.bbuf_val;
  if (pp->val_type == BINSON_ID_STRING)
  {
    return &pp->val.bbuf_val;
  }
  else {
    pp->error_flags = BINSON_ID_PARSE_WRONG_TYPE;
    return NULL;
  }
}
```
it will compile. Of course, if just using the commented line, this could be solved. Then the error handling must be in the application. However, what strategy to use is not yet decided.

**Comment by ppmag** [comment]
Claimed fixed in 55bdddeff3cc54d37c2103b39e26509136845e56.
Checking types is up to app from now.
